import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    height: '100vh',
    maxHeight: '100dvh',
    overflow: 'hidden',
    backgroundColor: '#0b1120',
    color: '#f8fafc',
    display: 'flex',
    flexDirection: 'column',
    padding: '6px 10px',
    fontFamily: 'system-ui, -apple-system, sans-serif',
    boxSizing: 'border-box',
  },
  manaSpeedSelector: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    backgroundColor: '#1e293b',
    border: '1px solid #334155',
    borderRadius: '6px',
    padding: '2px 6px',
  },
  manaSpeedLabel: {
    fontSize: '11px',
    color: '#60a5fa',
    fontWeight: 'bold',
    whiteSpace: 'nowrap',
  },
  manaSpeedSelect: {
    backgroundColor: '#0f172a',
    color: '#f8fafc',
    border: '1px solid #475569',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: 'bold',
    padding: '2px 4px',
    cursor: 'pointer',
    outline: 'none',
  },
  guideToggleButton: {
    backgroundColor: '#1e3a8a',
    color: '#bfdbfe',
    border: '1px solid #3b82f6',
    padding: '3px 8px',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 'bold',
    whiteSpace: 'nowrap',
  },
  resetButton: {
    backgroundColor: '#334155',
    color: '#fff',
    border: 'none',
    padding: '3px 8px',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 'bold',
    whiteSpace: 'nowrap',
  },
  mainLayout: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    maxWidth: '1160px',
    margin: '0 auto',
    display: 'flex',
    justifyContent: 'center',
    gap: '10px',
    overflow: 'hidden',
  },
  arenaColumn: {
    flex: 1,
    minHeight: 0,
    maxWidth: '780px',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#111827',
    borderRadius: '10px',
    padding: '6px 10px',
    border: '1px solid #1f2937',
    boxShadow: '0 8px 24px rgba(0,0,0,0.5)',
    boxSizing: 'border-box',
  },
  cpuHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: '32px',
    flexShrink: 0,
    paddingBottom: '3px',
    borderBottom: '1px solid #1f2937',
    width: '100%',
    boxSizing: 'border-box',
  },
  cpuHeaderControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    flexShrink: 0,
  },
  mobileCpuStatusGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flex: 1,
    minWidth: 0,
  },
  mobileCpuHpSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    flex: '1 1 auto',
    minWidth: 0,
    maxWidth: '120px',
  },
  mobileCpuName: {
    fontWeight: 'bold',
    fontSize: '11px',
    color: '#cbd5e1',
    whiteSpace: 'nowrap',
  },
  mobileCpuHpBarBg: {
    flex: 1,
    height: '14px',
    backgroundColor: '#030712',
    borderRadius: '7px',
    overflow: 'hidden',
    position: 'relative',
    border: '1px solid #374151',
  },
  mobileCpuManaSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    flex: '1 1 auto',
    minWidth: 0,
    maxWidth: '120px',
  },
  mobileCpuManaCount: {
    color: '#c084fc',
    fontSize: '11px',
    fontWeight: '600',
    whiteSpace: 'nowrap',
  },
  mobileCpuManaBarBg: {
    flex: 1,
    height: '14px',
    backgroundColor: '#030712',
    borderRadius: '7px',
    overflow: 'hidden',
    position: 'relative',
    border: '1px solid #7c3aed',
  },
  mobileCpuDeckSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '3px',
    flexShrink: 0,
  },
  mobileCpuDeckBadge: {
    backgroundColor: '#1e1b4b',
    border: '1px solid #6366f1',
    borderRadius: '4px',
    padding: '0 3px',
    fontSize: '10px',
    color: '#cbd5e1',
    fontWeight: 'bold',
    whiteSpace: 'nowrap',
  },
  cpuSpawnCircle: {
    position: 'absolute',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '46px',
    height: '46px',
    borderRadius: '50%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 15,
    pointerEvents: 'none',
  },
  cpuSpawnRing: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    borderRadius: '50%',
    border: '2px dashed #c084fc',
    animation: 'cpuRuneRotate 3s linear infinite',
    boxSizing: 'border-box',
  },
  cpuSpawnIcon: {
    fontSize: '20px',
    filter: 'drop-shadow(0 0 6px #c084fc)',
  },
  cpuSpawnBadge: {
    position: 'absolute',
    bottom: '-11px',
    backgroundColor: 'rgba(147, 51, 234, 0.92)',
    color: '#ffffff',
    fontSize: '8px',
    fontWeight: 'bold',
    padding: '1px 3px',
    borderRadius: '3px',
    whiteSpace: 'nowrap',
    boxShadow: '0 1px 3px rgba(0,0,0,0.6)',
  },
  playerInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flex: 1,
    minWidth: 0,
  },
  playerName: {
    fontWeight: 'bold',
    fontSize: '12px',
    color: '#cbd5e1',
    whiteSpace: 'nowrap',
  },
  hpBarBg: {
    flex: 1,
    maxWidth: '130px',
    minWidth: '50px',
    height: '15px',
    backgroundColor: '#030712',
    borderRadius: '7px',
    overflow: 'hidden',
    position: 'relative',
    border: '1px solid #374151',
  },
  hpBarFillCpu: {
    height: '100%',
    backgroundColor: '#ef4444',
    transition: 'width 0.2s',
  },
  hpBarFillPlayer: {
    height: '100%',
    backgroundColor: '#22c55e',
    transition: 'width 0.2s',
  },
  hpText: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    fontSize: '10px',
    fontWeight: 'bold',
    color: '#ffffff',
    textShadow: '0 1px 2px #000',
    whiteSpace: 'nowrap',
  },
  fieldGrid: {
    flex: 1,
    minHeight: '180px',
    display: 'grid',
    gridTemplateColumns: 'repeat(5, 1fr)',
    gap: '6px',
    position: 'relative',
    margin: '4px 0',
  },
  lane: {
    borderRadius: '6px',
    border: '1px solid #334155',
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    transition: 'background-color 0.12s, border-color 0.12s',
  },
  laneNumberTop: {
    fontSize: '10px',
    color: '#475569',
    fontWeight: 'bold',
    marginTop: '2px',
    pointerEvents: 'none',
    zIndex: 1,
  },
  laneNumberBottom: {
    fontSize: '10px',
    color: '#475569',
    fontWeight: 'bold',
    marginBottom: '2px',
    pointerEvents: 'none',
    zIndex: 1,
  },
  laneTrackLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: '50%',
    width: '1px',
    borderLeft: '1px dashed rgba(255,255,255,0.06)',
    pointerEvents: 'none',
  },
  summonGuideBadge: {
    position: 'absolute',
    bottom: '6px',
    left: '50%',
    transform: 'translate(-50%, 0)',
    backgroundColor: '#2563eb',
    color: '#fff',
    fontSize: '10px',
    padding: '2px 6px',
    borderRadius: '4px',
    fontWeight: 'bold',
    pointerEvents: 'none',
    zIndex: 15,
    animation: 'pulseSummonBadge 0.8s infinite ease-in-out',
    boxShadow: '0 0 10px rgba(37,99,235,0.7)',
    whiteSpace: 'nowrap',
  },
  dropZoneHint: {
    position: 'absolute',
    bottom: '6px',
    left: '50%',
    transform: 'translate(-50%, 0)',
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    border: '1px dashed rgba(96, 165, 250, 0.8)',
    color: '#93c5fd',
    fontSize: '9px',
    padding: '2px 5px',
    borderRadius: '3px',
    fontWeight: 'bold',
    pointerEvents: 'none',
    zIndex: 14,
    whiteSpace: 'nowrap',
  },
  unitWrapper: {
    position: 'absolute',
    left: '50%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    pointerEvents: 'none',
    zIndex: 10,
    willChange: 'top',
  },
  unitHpBarBg: {
    width: '28px',
    height: '4px',
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: '2px',
    overflow: 'hidden',
    marginBottom: '2px',
  },
  unitHpBarFill: {
    height: '100%',
    transition: 'width 0.1s',
  },
  unitBody: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  unitIconText: {
    fontSize: '19px',
    lineHeight: 1,
  },
  statusStun: {
    position: 'absolute',
    top: '-11px',
    fontSize: '8px',
    backgroundColor: '#eab308',
    color: '#000',
    padding: '1px 3px',
    borderRadius: '2px',
    fontWeight: 'bold',
  },
  statusSprint: {
    position: 'absolute',
    top: '-11px',
    fontSize: '8px',
    backgroundColor: '#06b6d4',
    color: '#000',
    padding: '1px 3px',
    borderRadius: '2px',
    fontWeight: 'bold',
  },
  statusBuff: {
    position: 'absolute',
    bottom: '-9px',
    fontSize: '8px',
    backgroundColor: '#ef4444',
    color: '#fff',
    padding: '1px 3px',
    borderRadius: '2px',
    fontWeight: 'bold',
  },
  statusBatBuff: {
    position: 'absolute',
    bottom: '-9px',
    fontSize: '8px',
    backgroundColor: '#9333ea',
    color: '#fff',
    padding: '1px 3px',
    borderRadius: '2px',
    fontWeight: 'bold',
    boxShadow: '0 0 6px rgba(147, 51, 234, 0.8)',
  },
  unitKillPopup: {
    position: 'absolute',
    top: '-24px',
    left: '50%',
    transform: 'translateX(-50%)',
    fontSize: '9px',
    fontWeight: 'bold',
    color: '#f43f5e',
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    border: '1px solid #f43f5e',
    borderRadius: '3px',
    padding: '1px 4px',
    whiteSpace: 'nowrap',
    pointerEvents: 'none',
    boxShadow: '0 0 8px rgba(244, 63, 94, 0.8)',
    animation: 'unit-kill-float 0.8s ease-out forwards',
    zIndex: 25,
  },
  unitBadges: {
    display: 'flex',
    gap: '3px',
    marginTop: '2px',
  },
  unitAtkBadge: {
    fontSize: '9px',
    backgroundColor: '#f59e0b',
    color: '#000',
    fontWeight: 'bold',
    padding: '0 3px',
    borderRadius: '2px',
    lineHeight: '13px',
  },
  unitHpBadge: {
    fontSize: '9px',
    backgroundColor: '#22c55e',
    color: '#000',
    fontWeight: 'bold',
    padding: '0 3px',
    borderRadius: '2px',
    lineHeight: '13px',
  },
  spellBlast: {
    position: 'absolute',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    backgroundColor: 'rgba(239, 68, 68, 0.92)',
    color: '#fff',
    padding: '4px 8px',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: 'bold',
    zIndex: 20,
    boxShadow: '0 0 15px #ef4444',
    whiteSpace: 'nowrap',
  },
  spellHaste: {
    backgroundColor: 'rgba(34, 197, 94, 0.92)',
    boxShadow: '0 0 15px #22c55e',
  },
  spellHeal: {
    backgroundColor: 'rgba(14, 165, 233, 0.92)',
    boxShadow: '0 0 15px #38bdf8',
  },
  spellBurn: {
    backgroundColor: 'rgba(249, 115, 22, 0.92)',
    boxShadow: '0 0 15px #ea580c',
  },
  playerCommandBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: '30px',
    flexShrink: 0,
    gap: '8px',
    padding: '3px 8px',
    backgroundColor: '#0f172a',
    borderRadius: '6px',
    border: '1px solid #1e293b',
    width: '100%',
    boxSizing: 'border-box',
    marginBottom: '6px',
  },
  playerHpSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    flex: '1 1 42%',
    minWidth: 0,
  },
  playerManaSection: {
    flex: '1 1 58%',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    minWidth: 0,
    maxWidth: '300px',
  },
  manaInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '11px',
    flexShrink: 0,
  },
  manaTitle: {
    color: '#94a3b8',
    fontWeight: '500',
  },
  manaCount: {
    color: '#60a5fa',
    fontSize: '12px',
    whiteSpace: 'nowrap',
  },
  manaBarBg: {
    flex: 1,
    minWidth: '50px',
    height: '14px',
    backgroundColor: '#030712',
    borderRadius: '7px',
    overflow: 'hidden',
    position: 'relative',
    border: '1px solid #2563eb',
  },
  manaBarFill: {
    height: '100%',
    backgroundColor: '#3b82f6',
    boxShadow: '0 0 8px rgba(59, 130, 246, 0.8)',
    transition: 'width 0.08s linear',
  },
  cpuManaBarFill: {
    height: '100%',
    backgroundColor: '#a855f7',
    boxShadow: '0 0 8px rgba(168, 85, 247, 0.8)',
    transition: 'width 0.08s linear',
  },
  manaTicks: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    justifyContent: 'space-between',
    pointerEvents: 'none',
    padding: '0 10%',
  },
  manaTick: {
    width: '1px',
    height: '100%',
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  dockContainer: {
    height: '100px',
    flexShrink: 0,
    display: 'flex',
    gap: '6px',
    alignItems: 'stretch',
    width: '100%',
    boxSizing: 'border-box',
  },
  nextCardSlot: {
    width: '64px',
    flexShrink: 0,
    backgroundColor: '#090d16',
    borderRadius: '6px',
    border: '1px dashed #334155',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '4px 2px',
    boxSizing: 'border-box',
    position: 'relative',
    userSelect: 'none',
  },
  nextBadge: {
    fontSize: '9px',
    fontWeight: 'bold',
    color: '#94a3b8',
    letterSpacing: '0.5px',
    backgroundColor: '#1e293b',
    padding: '1px 4px',
    borderRadius: '3px',
    lineHeight: 1,
  },
  nextCardInner: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '2px',
    width: '100%',
  },
  nextCardCostBadge: {
    fontSize: '9px',
    fontWeight: 'bold',
    color: '#fff',
    backgroundColor: '#1e40af',
    padding: '1px 4px',
    borderRadius: '3px',
    lineHeight: 1,
  },
  nextCardIcon: {
    fontSize: '18px',
    lineHeight: 1.1,
  },
  nextCardName: {
    fontSize: '9px',
    fontWeight: 'bold',
    color: '#cbd5e1',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '56px',
    textAlign: 'center',
  },
  nextCardEmpty: {
    color: '#475569',
    fontSize: '14px',
  },
  deckCountBadge: {
    fontSize: '9px',
    fontWeight: 'bold',
    color: '#60a5fa',
    backgroundColor: '#172554',
    padding: '1px 4px',
    borderRadius: '3px',
    lineHeight: 1,
    whiteSpace: 'nowrap',
  },
  cardLockBadge: {
    fontSize: '8px',
    fontWeight: 'bold',
    color: '#fff',
    backgroundColor: '#dc2626',
    padding: '0 3px',
    borderRadius: '2px',
    lineHeight: '12px',
  },
  handGrid: {
    height: '100%',
    flex: 1,
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '6px',
    boxSizing: 'border-box',
  },
  card: {
    backgroundColor: '#0f172a',
    borderRadius: '6px',
    border: '1.5px solid #334155',
    padding: '5px 4px',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    transition: 'all 0.15s ease',
    userSelect: 'none',
    boxSizing: 'border-box',
    overflow: 'hidden',
    touchAction: 'manipulation',
  },
  cardSelected: {
    borderColor: '#3b82f6',
    backgroundColor: '#1e3a8a',
    transform: 'translateY(-3px)',
    boxShadow: '0 4px 12px rgba(59, 130, 246, 0.5)',
  },
  cardHeader: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    lineHeight: 1,
  },
  cardCostBadge: {
    fontSize: '10px',
    fontWeight: 'bold',
    color: '#fff',
    padding: '1px 4px',
    borderRadius: '4px',
  },
  cardKeyBadge: {
    fontSize: '9px',
    color: '#64748b',
    fontWeight: 'bold',
  },
  cardCenter: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    margin: '1px 0',
  },
  cardIcon: {
    fontSize: '19px',
  },
  cardName: {
    fontSize: '12px',
    fontWeight: 'bold',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '75px',
  },
  cardFooter: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '1px',
  },
  cardStats: {
    display: 'flex',
    gap: '5px',
    fontSize: '10px',
    fontWeight: 'bold',
    lineHeight: 1,
  },
  cardSpellTag: {
    fontSize: '9px',
    color: '#fb923c',
    fontWeight: 'bold',
    lineHeight: 1,
  },
  cardSpellScope: {
    fontSize: '9px',
    color: '#fdba74',
    lineHeight: 1,
  },
  cardAtk: {
    color: '#f59e0b',
  },
  cardHp: {
    color: '#22c55e',
  },
  cardSpeed: {
    color: '#38bdf8',
  },
  cardDescSnippet: {
    fontSize: '9px',
    color: '#94a3b8',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '100%',
    textAlign: 'center',
    opacity: 0.85,
  },
  sidePanel: {
    width: '320px',
    flexShrink: 0,
    backgroundColor: '#111827',
    borderRadius: '10px',
    padding: '10px',
    border: '1px solid #1f2937',
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    boxSizing: 'border-box',
    boxShadow: '0 8px 24px rgba(0,0,0,0.5)',
    minHeight: 0,
  },
  sidePanelTitleRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '8px',
    paddingBottom: '6px',
    borderBottom: '1px solid #1f2937',
    flexShrink: 0,
  },
  sidePanelTitle: {
    fontSize: '13px',
    fontWeight: 'bold',
    color: '#f8fafc',
    letterSpacing: '-0.3px',
  },
  sidePanelBadge: {
    backgroundColor: '#1d4ed8',
    color: '#dbeafe',
    fontSize: '10px',
    padding: '2px 6px',
    borderRadius: '6px',
    fontWeight: 'bold',
  },
  sideBattleCard: {
    backgroundColor: '#0f172a',
    borderRadius: '8px',
    border: '1px solid #1e293b',
    padding: '8px 10px',
    marginBottom: '8px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    flexShrink: 0,
  },
  sideCpuStatusRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  sideCpuInfo: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    gap: '8px',
  },
  sideCpuName: {
    fontWeight: 'bold',
    fontSize: '12px',
    color: '#cbd5e1',
    whiteSpace: 'nowrap',
  },
  sideHpBarBg: {
    flex: 1,
    maxWidth: '160px',
    minWidth: '70px',
    height: '16px',
    backgroundColor: '#030712',
    borderRadius: '8px',
    overflow: 'hidden',
    position: 'relative',
    border: '1px solid #374151',
  },
  sideCpuManaRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    gap: '8px',
  },
  cpuManaTitle: {
    color: '#cbd5e1',
    fontWeight: '500',
    fontSize: '11px',
  },
  cpuManaCount: {
    color: '#c084fc',
    fontSize: '12px',
    whiteSpace: 'nowrap',
  },
  sideCpuManaBarBg: {
    flex: 1,
    maxWidth: '160px',
    minWidth: '70px',
    height: '14px',
    backgroundColor: '#030712',
    borderRadius: '7px',
    overflow: 'hidden',
    position: 'relative',
    border: '1px solid #7c3aed',
  },
  sideCpuHandRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    width: '100%',
    padding: '4px 6px',
    backgroundColor: '#0a0f1d',
    borderRadius: '6px',
    border: '1px solid #1e293b',
    boxSizing: 'border-box',
  },
  sideCpuHandHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  sideCpuHandTitle: {
    fontSize: '11px',
    color: '#94a3b8',
    fontWeight: '500',
  },
  sideCpuDeckCount: {
    fontSize: '11px',
    color: '#a78bfa',
    fontWeight: 'bold',
  },
  sideCpuHandCards: {
    display: 'flex',
    gap: '6px',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  sideCpuCardSlot: {
    width: '26px',
    height: '36px',
    borderRadius: '4px',
    backgroundColor: '#1e1b4b',
    border: '1px solid #6366f1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 2px 4px rgba(0,0,0,0.4)',
    overflow: 'hidden',
  },
  cpuCardBack: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(135deg, #312e81 0%, #1e1b4b 100%)',
  },
  cpuCardBackPattern: {
    color: '#818cf8',
    fontSize: '11px',
    opacity: 0.85,
  },
  sideControlRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '6px',
    width: '100%',
    paddingTop: '2px',
  },
  sidePanelHeader: {
    display: 'flex',
    gap: '4px',
    marginBottom: '8px',
    borderBottom: '1px solid #1f2937',
    paddingBottom: '6px',
    flexShrink: 0,
  },
  tabButton: {
    flex: 1,
    backgroundColor: 'transparent',
    border: 'none',
    color: '#94a3b8',
    padding: '5px 8px',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 'bold',
    transition: 'all 0.15s ease',
  },
  tabButtonActive: {
    backgroundColor: '#1e293b',
    color: '#60a5fa',
  },
  sidePanelContent: {
    flex: 1,
    overflowY: 'auto',
    paddingRight: '2px',
    minHeight: 0,
  },
  tipsSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  tipBox: {
    backgroundColor: '#0f172a',
    borderRadius: '6px',
    padding: '8px 10px',
    border: '1px solid #1e293b',
  },
  tipTitle: {
    fontSize: '11px',
    fontWeight: 'bold',
    color: '#93c5fd',
    marginBottom: '3px',
  },
  tipText: {
    fontSize: '11px',
    color: '#cbd5e1',
    lineHeight: '1.4',
  },
  shortcutGuide: {
    backgroundColor: '#1e293b',
    padding: '8px',
    borderRadius: '6px',
    fontSize: '11px',
    color: '#94a3b8',
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    marginTop: '4px',
  },
  catalogList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  catalogItem: {
    backgroundColor: '#0f172a',
    borderRadius: '6px',
    padding: '6px 8px',
    border: '1px solid #1e293b',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  catalogItemIcon: {
    fontSize: '22px',
    width: '28px',
    textAlign: 'center',
    flexShrink: 0,
  },
  catalogItemInfo: {
    flex: 1,
    minWidth: 0,
  },
  catalogItemTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  catalogItemName: {
    fontSize: '12px',
    fontWeight: 'bold',
    color: '#f8fafc',
  },
  catalogItemCost: {
    fontSize: '11px',
    fontWeight: 'bold',
    color: '#60a5fa',
  },
  catalogItemStats: {
    display: 'flex',
    gap: '8px',
    fontSize: '10px',
    color: '#94a3b8',
    margin: '2px 0',
  },
  catalogItemDesc: {
    fontSize: '10px',
    color: '#64748b',
    lineHeight: '1.3',
  },
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.8)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    backdropFilter: 'blur(3px)',
  },
  modal: {
    backgroundColor: '#1e293b',
    borderRadius: '12px',
    padding: '24px',
    maxWidth: '420px',
    textAlign: 'center',
    border: '1px solid #475569',
    boxShadow: '0 10px 30px rgba(0,0,0,0.7)',
  },
  modalTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    marginBottom: '12px',
  },
  modalMessage: {
    fontSize: '14px',
    color: '#cbd5e1',
    lineHeight: '1.5',
    marginBottom: '20px',
  },
  modalButton: {
    backgroundColor: '#2563eb',
    color: '#fff',
    border: 'none',
    padding: '10px 24px',
    borderRadius: '6px',
    fontSize: '15px',
    fontWeight: 'bold',
    cursor: 'pointer',
    transition: 'background-color 0.15s',
  },
  guideModal: {
    backgroundColor: '#111827',
    borderRadius: '10px',
    padding: '14px',
    maxWidth: '440px',
    width: '92%',
    maxHeight: '80vh',
    display: 'flex',
    flexDirection: 'column',
    border: '1px solid #374151',
    boxShadow: '0 10px 30px rgba(0,0,0,0.8)',
  },
  guideModalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
    gap: '8px',
  },
  guideModalCloseBtn: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#94a3b8',
    fontSize: '18px',
    cursor: 'pointer',
    padding: '4px 8px',
    lineHeight: 1,
  },
  guideModalBody: {
    flex: 1,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    minHeight: 0,
  },
};
